import React,{useEffect,useState} from 'react';
import {GoogleLogo,DiscordLogo,Eye,EyeSlash,EnvelopeSimpleOpen} from '@phosphor-icons/react';
import {pilotApi as api} from '../services/pilotApi.js';
import './account.css';

export default function AuthPanel({user,onUser,onClose,initialMode='magic',onGuest}){
 const [mode,setMode]=useState(initialMode),[providers,setProviders]=useState(null),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[showPassword,setShowPassword]=useState(false),[emailSent,setEmailSent]=useState(null);
 useEffect(()=>{let active=true;api.providers().then(p=>active&&setProviders(p)).catch(()=>active&&setNote('Account service unavailable. Please try again.'));return()=>{active=false;};},[]);
 const titles={magic:'Sign in with email',login:'Sign in',signup:'Create your account',recover:'Reset your password',reset:'Choose a new password'};
 const change=m=>{setMode(m);setNote('');setEmailSent(null);setShowPassword(false);};
 async function submit(e){e.preventDefault();setBusy(true);setNote('');const d=Object.fromEntries(new FormData(e.currentTarget));try{if(mode==='magic'){await api.magic(d);setEmailSent({kind:'magic',email:d.email});}else if(mode==='recover'){await api.recover({email:d.email});setEmailSent({kind:'recovery',email:d.email});}else if(mode==='reset'){await api.password({password:d.password});setNote('Password updated. You can continue researching.');}else{const r=await api[mode](d);if(r.status==='check-email')setEmailSent({kind:'signup',email:d.email});else{onUser(r);onClose();}}}catch(e){setNote(({EMAIL_NOT_CONFIRMED:'Please verify your email before signing in.',AUTH_RATE_LIMITED:'Too many attempts. Please wait before trying again.',AUTH_FAILED:'We couldn’t complete that request. Check your details and try again.'})[e.message]||'Account service unavailable. Please try again.');}finally{setBusy(false);}}
 async function social(provider){setBusy(true);setNote('');try{const r=await api.provider(provider);location.assign(r.url);}catch{setNote('This sign-in method could not start. Try email or return later.');setBusy(false);}}

 if(emailSent)return <div className="auth-panel account-refined account-confirmation"><img className="account-guide" src={import.meta.env.BASE_URL+'images/cleisthenes.png'} alt=""/><EnvelopeSimpleOpen className="account-confirmation-icon" size={34} aria-hidden="true"/><h2 id="account-title">{emailSent.kind!=='recovery'?'Check your email':'Recovery email sent'}</h2><p>We sent a private link to <strong>{emailSent.email}</strong>. Open it in this browser within one hour.</p><p className="account-confirmation-detail">{emailSent.kind==='magic'?'Click the link to sign in securely. No password needed.':emailSent.kind==='signup'?'The link returns you to midnight.vote and completes your account.':'The link returns you to midnight.vote so you can choose a new password.'}</p>{emailSent.kind==='signup'&&<button className="account-submit" onClick={()=>change('login')}>Sign in after verifying</button>}<button className="account-text-button" onClick={()=>change(emailSent.kind==='magic'?'magic':emailSent.kind==='signup'?'signup':'recover')}>Use another email address</button>{onGuest&&<button className="account-guest" onClick={onGuest}>Explore without an account →</button>}</div>;

 const intro=mode==='magic'?'We’ll email you a secure sign-in link. New here? This also creates your account.':mode==='recover'?'Enter the email address associated with your account.':mode==='reset'?'Use at least eight characters for your new password.':'';
 const socialMethods=[['google','Google',GoogleLogo],['discord','Discord',DiscordLogo]];
 return <div className="auth-panel account-refined"><img className="account-guide" src={import.meta.env.BASE_URL+'images/cleisthenes.png'} alt=""/><h2 id="account-title">{user&&mode!=='reset'?'Your account':titles[mode]}</h2>
 {user&&mode!=='reset'?<><p>{user.firstName||user.name?.split(/\s+/)[0]||user.email}</p><small>{user.email}</small><button className="account-submit" disabled={busy} onClick={async()=>{setBusy(true);try{await api.logout();onUser(null);onClose();}catch{setNote('Sign-out failed. Please try again.');}finally{setBusy(false);}}}>Sign out</button></>:<>
 {intro&&<p className="account-intro">{intro}</p>}
 {providers?.email?<form onSubmit={submit}>{mode==='signup'&&<label>Name<input name="name" type="text" required maxLength={100} autoComplete="name" placeholder="Your name"/></label>}{mode!=='reset'&&<label>Email address<input name="email" type="email" required maxLength={254} autoComplete="email" placeholder="you@example.ch"/></label>}{!['recover','magic'].includes(mode)&&<label>Password<div className="account-password"><input name="password" type={showPassword?'text':'password'} required minLength={8} maxLength={256} autoComplete={mode==='login'?'current-password':'new-password'}/><button type="button" aria-label={showPassword?'Hide password':'Show password'} onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeSlash size={19}/>:<Eye size={19}/>}</button></div>{mode!=='login'&&<small>At least 8 characters</small>}</label>}<button className="account-submit" disabled={busy}>{busy?'Please wait…':({magic:'Email me a sign-in link',login:'Sign in',signup:'Create my account',recover:'Send recovery link',reset:'Update password'})[mode]}</button></form>:<p role="status">{providers?'Email accounts are unavailable.':'Connecting to account service…'}</p>}
 <div className="auth-links">{mode==='magic'?<button disabled={busy} onClick={()=>change('login')}>Use a password instead</button>:mode==='signup'?<span>Already have an account? <button disabled={busy} onClick={()=>change('login')}>Sign in</button></span>:mode==='login'?<><button disabled={busy} onClick={()=>change('signup')}>Create an account</button><button disabled={busy} onClick={()=>change('recover')}>Forgot password?</button></>:<button disabled={busy} onClick={()=>change('login')}>Back to sign in</button>}</div>
 {['magic','login','signup'].includes(mode)&&<div className="account-provider-stack" aria-label="Other sign-in methods"><div className="account-providers">{socialMethods.map(([id,label,Icon])=><button key={id} type="button" disabled={busy||!providers?.[id]} onClick={()=>social(id)} aria-label={'Continue with '+label+(!providers?.[id]?' — not enabled':'')}><Icon size={21}/><span>{label}</span></button>)}</div></div>}
 {mode==='login'&&<button className="account-text-button" disabled={busy} onClick={()=>change('magic')}>Email me a sign-in link</button>}{onGuest&&<button className="account-guest" onClick={onGuest}>Explore without an account →</button>}</>}
 {note&&<p className="account-notice" role="status">{note}</p>}</div>;
}
