import React,{useEffect,useState} from 'react';
import {CalendarBlank,CaretLeft,CaretRight,ChatCircleDots,PaperPlaneTilt,X} from '@phosphor-icons/react';
import {pilotApi as api} from '../services/pilotApi.js';
import FollowButton from './FollowButton.jsx';
import ParliamentAgenda from './ParliamentAgenda.jsx';
import './agenda.css';
import {loadConversations} from './chat-history.mjs';
import './dashboard-feedback.css';
import {NextVoteCard} from './VoteCompanion.jsx';

const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Zurich',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const cantons='AG AI AR BE BL BS FR GE GL GR JU LU NE NW OW SG SH SO SZ TG TI UR VD VS ZG ZH'.split(' ');
const monthNames=['January','February','March','April','May','June','July','August','September','October','November','December'];
const formatMonth=value=>{const [year,index]=value.split('-').map(Number);return `${monthNames[index-1]} ${year}`;};
const shiftMonth=(value,delta)=>{const [year,index]=value.split('-').map(Number),next=new Date(Date.UTC(year,index-1+delta,1));return `${next.getUTCFullYear()}-${String(next.getUTCMonth()+1).padStart(2,'0')}`;};

function MiniChamber({snapshot,onOpen}){
 if(!snapshot)return <span className="mini-chamber-loading" aria-hidden="true"/>;
 const colors=new Map(snapshot.parties.map(p=>[p.id,p.color]));
 return <button className="mini-chamber" onClick={onOpen} aria-label="Open the verified National Council chamber"><svg viewBox="0 0 860 565" role="img" aria-label={`Verified National Council seating snapshot, ${snapshot.counts.occupied} occupied seats`}><g className="mini-chamber-architecture">{snapshot.architecture.map((path,index)=><path key={index} d={path}/>)}</g>{snapshot.seats.map(seat=><path key={seat.seatId} d={seat.geometry.path} fill={colors.get(seat.member?.partyId)||'#d9cbb4'}/>)}</svg><span>Open chamber</span></button>;
}

export default function Dashboard({user,dossiers,onNavigate,onAsk,onAccount,language='en'}){
 const [data,setData]=useState(null),[period,setPeriod]=useState('today'),[calendarDay,setCalendarDay]=useState(null),[calendarEvent,setCalendarEvent]=useState(null),[month,setMonth]=useState(today().slice(0,7)),[pickerYear,setPickerYear]=useState(Number(today().slice(0,4))),[monthPicker,setMonthPicker]=useState(false),[follows,setFollows]=useState([]),[following,setFollowing]=useState(false),[recent,setRecent]=useState([]),[canton,setCanton]=useState(''),[error,setError]=useState(''),[parties,setParties]=useState([]),[chamber,setChamber]=useState(null),[chatDraft,setChatDraft]=useState('');
 useEffect(()=>{let live=true;const refresh=()=>api.dashboard().then(d=>live&&setData(d)).catch(()=>live&&setError('Dashboard unavailable. Please try again.'));refresh();const timer=setInterval(refresh,1800000);api.chamber('nr').then(s=>{if(live){setChamber(s);setParties(s.parties);}}).catch(()=>{});return()=>{live=false;clearInterval(timer);};},[]);
 useEffect(()=>{let live=true;setFollows([]);setCanton('');const load=()=>{if(user){api.items('follow').then(r=>live&&setFollows(r.map(x=>({...x.payload,key:x.id})))).catch(()=>live&&setError('Could not load your follows.'));api.items('conversation').then(r=>live&&setRecent(r.map(x=>x.payload).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,3))).catch(()=>{});api.items('preference').then(r=>live&&setCanton(r.find(x=>x.id==='canton')?.payload.value||'')).catch(()=>{});}else setRecent(loadConversations(localStorage).slice(0,3));};load();addEventListener('follows-changed',load);return()=>{live=false;removeEventListener('follows-changed',load);};},[user?.id]);
 const events=[...(data?.agenda.events||[]),...dossiers.map(d=>({id:'vote-'+d.id,title:d.shortTitle.en,type:'popular-vote',date:d.date,status:'completed',dossierId:d.id,sourceUrl:'?issue='+d.id}))],date=today();
 const shown=events.filter(e=>period==='today'?(e.date===date||e.type==='session'&&e.date<=date&&e.endDate>=date):period==='upcoming'?e.date>date:e.date<date);if(period==='previous')shown.reverse();
 const start=new Date(month+'-01T12:00:00Z'),offset=(start.getUTCDay()+6)%7,count=new Date(start.getUTCFullYear(),start.getUTCMonth()+1,0).getDate();
 const items=(data?.feed.items||[]).filter(i=>!following||follows.some(f=>f.kind==='business'&&f.id===i.businessId));
 const calendarEvents=calendarDay?events.filter(e=>e.date===calendarDay):[];
 const displayName=user?.firstName||user?.name?.trim().split(/\s+/)[0]||'Citizen';
 function pickDay(value){const matches=events.filter(e=>e.date===value);setCalendarDay(value);setCalendarEvent(matches[0]||null);}
 function moveMonth(delta){const next=shiftMonth(month,delta);setMonth(next);setPickerYear(Number(next.slice(0,4)));setMonthPicker(false);setCalendarDay(null);setCalendarEvent(null);}
 function askFromHome(event){event.preventDefault();const prompt=chatDraft.trim();if(!prompt)return;onAsk(null,{prompt,autoSend:true});setChatDraft('');}
 return <section className="civic-dashboard"><div className="workspace-heading dashboard-welcome"><h1>Welcome, {displayName}.</h1><span className="today-stamp">{new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Zurich',weekday:'long',day:'numeric',month:'long'}).format(new Date())}<small>Europe / Zurich</small></span></div>
 <NextVoteCard language={language}/>
 <form className="dashboard-chat" onSubmit={askFromHome}><ChatCircleDots size={24} aria-hidden="true"/><label className="sr-only" htmlFor="dashboard-chat-input">Ask Cleisthenes</label><input id="dashboard-chat-input" value={chatDraft} onChange={e=>setChatDraft(e.target.value)} placeholder="Ask Cleisthenes about Parliament, a proposal or a public statement…" maxLength={500}/><button aria-label="Ask Cleisthenes" disabled={!chatDraft.trim()}><PaperPlaneTilt size={20}/></button></form>
 <div className="dashboard-shortcuts"><button onClick={()=>onNavigate(null,'parliament')}><span>Explore the chambers</span><strong>246 representatives ↗</strong></button><button onClick={()=>onNavigate(null,'explore')}><span>Understand a proposal</span><strong>Topics & votes ↗</strong></button><button onClick={()=>onNavigate(null,'saved')}><span>Your personal library</span><strong>Saved research ↗</strong></button></div>
 {error&&<p role="status">{error}</p>}<div className="dashboard-grid"><ParliamentAgenda events={events} language={language} loading={!data} retrievedAt={data?.agenda.retrievedAt} stale={data?.agenda.stale} chamberSlot={<div className="agenda-chamber"><MiniChamber snapshot={chamber} onOpen={()=>onNavigate(null,'parliament')}/><div><strong>{language==='fr'?'Les chambres':'The chambers'}</strong><small>{language==='fr'?'Conseil national · 200 sièges':'National Council · 200 seats'}</small><small>{language==='fr'?'Conseil des Etats · 46 sièges':'Council of States · 46 seats'}</small><button className="text-button" onClick={()=>onNavigate(null,'parliament')}>{language==='fr'?'Voir qui siège →':'See who sits where →'}</button></div></div>} onAsk={onAsk} onNavigate={onNavigate}/>
<section className="workspace-card follows"><h2>Your follows</h2><p>Choose what you want to keep up with. These choices never imply a political affiliation.</p>{follows.map(f=><div className="followed-row" key={f.key}><span>{f.title}<small>{f.kind}</small></span><FollowButton user={user} kind={f.kind} id={f.id} title={f.title} onAccount={onAccount}/></div>)}{!follows.length&&<p className="muted">Follow a person in Parliament, or choose a topic or party below.</p>}<details><summary>Choose topics & parties</summary>{dossiers.map(d=><div className="followed-row" key={d.id}><span>{d.shortTitle.en}</span><FollowButton user={user} kind="topic" id={d.id} title={d.shortTitle.en} onAccount={onAccount}/></div>)}{parties.map(p=><div className="followed-row" key={p.id}><span>{p.abbreviation} · {p.name}</span><FollowButton user={user} kind="party" id={p.id} title={p.name} onAccount={onAccount}/></div>)}</details><label className="canton-choice">Canton (optional)<select value={canton} onChange={async e=>{if(!user){onAccount();return;}const value=e.target.value;try{await api.putItem('preference','canton',{value});setCanton(value);}catch{setError('Canton preference could not be saved.');}}}><option value="">All Switzerland</option>{cantons.map(c=><option key={c}>{c}</option>)}</select></label><small>Your canton is a preference, not proof of residence. Local feed coverage is not available yet.</small></section>
 <section className="workspace-card"><h2>Recent research</h2>{recent.length?recent.map(c=><button key={c.id} className="recent-research" onClick={()=>{onNavigate(null,'chat');window.dispatchEvent(new CustomEvent('open-conversation',{detail:c.id}));}}><strong>{c.messages.find(m=>m.role==='user')?.text||'Conversation'}</strong><small>{c.scope?.title||'Parliament'} · {new Date(c.updatedAt).toLocaleDateString('en-GB')}</small></button>):<p className="empty-state">Your conversations will appear here as you explore.</p>}<button className="secondary" onClick={()=>onNavigate(null,'chats')}>See all chats</button> <button className="secondary" onClick={()=>onNavigate(null,'saved')}>Open saved research →</button></section></div>
 <section className="news-section"><div className="workspace-heading"><div><p className="eyebrow">From the public record</p><h2>News & updates</h2></div><div className="workspace-segments"><button aria-pressed={!following} onClick={()=>setFollowing(false)}>All updates</button><button aria-pressed={following} onClick={()=>setFollowing(true)}>Following</button></div></div><p className="muted">{following?'Updates linked to proposals you explicitly follow. No matching update is inferred from political interests.':'Official proposal updates from the imported collection.'} {data?.feed.stale?'Source snapshot is more than 24 hours old.':''}</p><div className="updates-grid">{items.slice(0,6).map(i=><article key={i.id}><small>{i.publisher} · {i.date?.slice(0,10)}</small><h3>{i.title}</h3><p>{i.stage}</p><div className="member-actions"><a href={i.sourceUrl} target="_blank" rel="noreferrer">Original record ↗</a><button onClick={()=>onAsk({kind:'business',id:i.businessId,title:i.title},{prompt:'Explain this proposal using its available parliamentary sources.'})}>Ask Cleisthenes</button></div><FollowButton user={user} kind="business" id={i.businessId} title={i.title} onAccount={onAccount}/></article>)}</div>{!items.length&&<p>No matching updates in the current imported collection.</p>}<div className="publisher-links"><strong>Public-service reporting</strong>{data?.feed.publishers.map(p=><a key={p.id} href={p.url} target="_blank" rel="noreferrer">{p.name} ↗</a>)}<small>Read on the publisher’s site. Article syndication awaits verified reuse permission.</small></div></section>
 </section>;
}
