import React,{useEffect,useState,useRef} from 'react';
import {ArrowRight,ArrowCounterClockwise,Play,Pause,Check,ShieldCheck,LockKey,Fingerprint,MagnifyingGlass,Translate,Quotes,MapPin} from '@phosphor-icons/react';
import './landing-demos.css';
const asset=name=>import.meta.env.BASE_URL+'brand/'+name;
const steps=['Search the debate','Open the quotation','Find the exact moment','Read it in English'];
function DemoHeader({children}){return <div className="walkthrough-label"><span>Interactive preview</span><span>{children}</span></div>;}
// Real debate on the 10-million initiative: one voice for and one against, each with its official video
// moment (machine-aligned, review pending), original words and a labelled machine translation.
const TEN_MILLION=[
 {id:'for',side:'For the initiative',speaker:'Lorenzo Quadri',meta:'National Council · Lega dei Ticinesi · Ticino',date:'25 September 2025',language:'Italian',video:'https://par-pcache.simplex.tv/content/simvid_1.mp4?externalid=364201',start:173.52,end:222.72,
  original:'Tutelarsi è legittimo. L’iniziativa popolare "No ad una Svizzera da 10 milioni" non è di per sé un’iniziativa contro la libera circolazione delle persone e quindi contro i Bilaterali, perché – il testo è chiaro – quando si raggiungono i limiti indicati si interviene sul settore dell’asilo e sui ricongiungimenti familiari.',
  english:'Seeking protection is legitimate. The popular initiative "No to a Switzerland of 10 million" is not in itself an initiative against the free movement of persons and therefore against the Bilateral Agreements, because – the text is clear – when the stated limits are reached, action is taken in the area of asylum and family reunification.',
  source:'https://www.parlament.ch/fr/ratsbetrieb/amtliches-bulletin/amtliches-bulletin-die-verhandlungen?SubjectId=69350&TranscriptId=364201'},
 {id:'against',side:'Against the initiative',speaker:'Céline Weber',meta:'National Council · Green Liberal Party · Vaud',date:'22 September 2025',language:'French',video:'https://par-pcache.simplex.tv/content/simvid_1.mp4?externalid=363295',start:2.4,end:31.6,
  original:'Le constat est clair. Il suffit d’écouter les gens sur les marchés le samedi matin : une Suisse à 10 millions ne fait pas rêver ou alors que très peu de gens. Oui, la Suisse se questionne sur l’évolution de sa démographie et ne rien faire n’est pas une option.',
  english:'The conclusion is clear. Just listen to people in the markets on Saturday mornings: a Switzerland of 10 million does not inspire much enthusiasm, or very few people. Yes, Switzerland is questioning the evolution of its demographics, and doing nothing is not an option.',
  source:'https://www.parlament.ch/fr/ratsbetrieb/amtliches-bulletin/amtliches-bulletin-die-verhandlungen?SubjectId=69261&TranscriptId=363295'}];
const clock=n=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
export function ResearchDemo({onExplore,reduceMotion}){
 const [side,setSide]=useState('for'),[translated,setTranslated]=useState(false),[failed,setFailed]=useState(false),player=useRef(null);
 const moment=TEN_MILLION.find(m=>m.id===side);
 useEffect(()=>{setTranslated(false);setFailed(false);},[side]);
 function play(){const v=player.current;if(v){v.currentTime=moment.start;v.play().catch(()=>setFailed(true));}}
 return <div className="landing-walkthrough real-research" data-still={reduceMotion}><DemoHeader>Real debate · September 2025</DemoHeader><div className="mini-app-bar"><img src={asset('cleisthenes-bust.png')} alt=""/><strong>Cleisthenes</strong><span>No to a Switzerland of 10 million · 25.026</span></div><div className="research-demo-body"><div className="demo-search"><MagnifyingGlass/><span>What are the arguments for and against?</span></div>
  <div className="demo-sides" role="tablist" aria-label="Positions">{TEN_MILLION.map(m=><button key={m.id} role="tab" aria-selected={side===m.id} onClick={()=>setSide(m.id)}><small>{m.side}</small>{m.speaker}</button>)}</div>
  <video key={moment.id} ref={player} controls playsInline preload="metadata" src={`${moment.video}#t=${moment.start},${moment.end}`} onLoadedMetadata={e=>{e.currentTarget.currentTime=moment.start;}} onTimeUpdate={e=>{if(e.currentTarget.currentTime>=moment.end&&!e.currentTarget.paused)e.currentTarget.pause();}} onError={()=>setFailed(true)}/>
  <div className="demo-quote"><small>{moment.speaker} · {moment.meta} · {moment.date}</small><span className="quote-language">{translated?'English · machine translation':`${moment.language} · original words`}</span><blockquote>{translated?moment.english:moment.original}</blockquote><div className="real-demo-actions"><button className="timestamp-chip" onClick={play}><Play/> {clock(moment.start)}–{clock(moment.end)} · Play passage</button><button className="demo-action" onClick={()=>setTranslated(!translated)}><Translate/>{translated?'Read original':'Read in English'}</button></div>{failed&&<p role="status">Video playback is unavailable here. Read the official source below.</p>}<small>Timing matched with NVIDIA Canary. Human timing review pending. The quotation is an excerpt from this passage.</small></div></div>
  <div className="demo-footnote"><a href={moment.source} target="_blank" rel="noreferrer">© ParlCH · Official Bulletin ↗</a><button onClick={onExplore}>Ask Cleisthenes about both sides <ArrowRight/></button></div></div>;
}
export function PrivacyDemo({reduceMotion}){
 const [step,setStep]=useState(0),[canton,setCanton]=useState(true),[running,setRunning]=useState(false);
 useEffect(()=>{if(!running)return;const timer=setTimeout(()=>{setStep(s=>s+1);if(step===1)setRunning(false);},1500);return()=>clearTimeout(timer);},[running,step]);
 return <div className="landing-walkthrough privacy-walkthrough" data-still={reduceMotion}><DemoHeader>Identity concept · no data collected</DemoHeader><div className="privacy-stage"><div className="proof-phone"><div className="phone-island"/><div className="phone-heading"><LockKey size={18}/><span>Private on your device</span></div><div className={'phone-emblem '+(running?'proof-pulse':'')}><Fingerprint size={56}/></div><h4>{step===0?'Your identity.':step===1?'Creating a proof…':'Ready to share.'}</h4><p>{step===0?'Only you see the details.':step===1?'Checking eligibility locally.':'Only the selected claims leave.'}</p><div className="private-field"><span>Name</span><b>•••• •••••</b><LockKey/></div><div className="private-field"><span>Address</span><b>••••••••••</b><LockKey/></div><div className="private-field"><span>Identity document</span><b>On device</b><LockKey/></div><div className="phone-bottom"><ShieldCheck/> Personal details stay here</div></div><div className={'proof-bridge '+(step===1?'is-active':'')} aria-hidden="true"><span/><ArrowRight/></div><div className={'proof-receipt '+(step===2?'is-confirmed':'')}><img className="midnight-network-logo" src={asset('midnight-network.svg')} alt="Midnight Network"/><span className="demo-kicker">{step===2?'Illustrative proof received':'Only what is needed'}</span><h4>Eligible to take part.</h4><ul><li><Check/> Swiss citizen</li><li><Check/> Aged 18 or over</li>{canton&&<li><MapPin/> Canton: Geneva</li>}</ul><small>{step===2?'Proof preview complete':'Waiting for your permission'}</small></div></div><div className="privacy-options"><label><input type="checkbox" checked={canton} disabled={running} onChange={e=>{setCanton(e.target.checked);setStep(0);}}/> Include canton for a local question <small>Example: Geneva</small></label><button className="play-walkthrough" disabled={running} onClick={()=>{setStep(0);setRunning(true);}}>{step===2?<ArrowCounterClockwise/>:<ShieldCheck/>}{running?'Creating proof…':step===2?'Replay proof flow':'See the proof flow'}</button></div><div className="privacy-boundary"><LockKey/><p><strong>Not shared:</strong> name, address, full birth date, identity document or other unnecessary personal details.</p></div><div className="demo-footnote"><span>Simulated future flow. No identity check or network transaction runs here.</span></div></div>;
}
export function ParticipateDemo({onExplore,reduceMotion}){
 const [phase,setPhase]=useState('ready'),[angle,setAngle]=useState(''),[choice,setChoice]=useState('');
 useEffect(()=>{if(!['thinking','confirming'].includes(phase))return;const timer=setTimeout(()=>setPhase(phase==='thinking'?'answer':'done'),phase==='thinking'?1700:1200);return()=>clearTimeout(timer);},[phase]);
 function ask(value){setAngle(value);setPhase('thinking');setChoice('');}
 return <div className="landing-walkthrough participate-walkthrough" data-still={reduceMotion}><DemoHeader>Fictional proposal · non-binding demo</DemoHeader><div className="demo-chat-header"><img src={asset('cleisthenes-bust.png')} alt=""/><div><strong>Cleisthenes</strong><small>Your civic companion · sample conversation</small></div><button aria-label="Restart participation demo" onClick={()=>{setPhase('ready');setChoice('');setAngle('');}}><ArrowCounterClockwise/></button></div><div className="demo-conversation"><span className="context-pill">Neighbourhood square · evening traffic</span><p className="demo-assistant">A proposal would close the square to through-traffic three evenings a week. What would you like to understand?</p><div className="demo-question-chips"><button disabled={phase==='thinking'||phase==='confirming'} onClick={()=>ask('benefit')}>What could improve?</button><button disabled={phase==='thinking'||phase==='confirming'} onClick={()=>ask('concern')}>What is the main concern?</button></div>{phase!=='ready'&&<div className="sample-user">{angle==='benefit'?'What could improve?':'What is the main concern?'}</div>}<div aria-live="polite">{phase==='thinking'?<p className="demo-thinking"><span/><span/><span/> Reading the sample proposal…</p>:phase!=='ready'&&<div className="demo-response"><p>{angle==='benefit'?'Fewer through-cars could make the square quieter and easier to enjoy in the evenings. The trade-off is that traffic may shift to nearby streets.':'Traffic may shift to nearby streets, and some journeys could become less convenient. Supporters argue that a quieter square would benefit residents.'}</p><small><Quotes/> Sample proposal · §2–3 · scripted explanation</small></div>}</div>{['answer','confirming','done'].includes(phase)&&<div className="demo-ballot"><span className="demo-kicker">Try a community temperature check</span><h4>Would you support a trial?</h4>{phase==='done'?<div className="demo-vote-done" role="status"><Check size={26}/><strong>Demo choice confirmed: {choice}</strong><p>Nothing was submitted or stored. This is how a future participation flow could feel.</p></div>:<><div className="ballot-options">{['Yes','No','Undecided'].map(v=><button key={v} disabled={phase==='confirming'} aria-pressed={choice===v} onClick={()=>setChoice(v)}>{v}</button>)}</div><button className={'fingerprint-confirm '+(phase==='confirming'?'is-confirming':'')} disabled={!choice||phase==='confirming'} onClick={()=>setPhase('confirming')}><Fingerprint size={30}/>{phase==='confirming'?'Confirming demo choice…':'Confirm demo choice'}</button><small>Fingerprint animation only · no biometric access</small></>}</div>}</div><div className="demo-footnote"><span>A simulation, not an official ballot.</span><button onClick={onExplore}>Explore topics & votes <ArrowRight/></button></div></div>;
}
