import React from 'react';
export default function LegalNotice({kind='privacy'}){
 return <article className="account-legal"><p className="eyebrow">Independent Swiss pilot · Updated 24 September 2026</p><h2>{kind==='privacy'?'Privacy & your data':'Pilot terms of use'}</h2>{kind==='privacy'?<>
 <p>Public parliamentary information is available without an account. If you sign in, we store your email, profile choices, saved sources, follows, preferences and conversations you create while signed in. Profile pictures are optional.</p>
 <h3>Where information goes</h3><p>Supabase handles authentication and account records. Hostinger hosts this application; Titan sends authentication emails. When you ask Cleisthenes a question, your question, relevant conversation context and retrieved passages are sent to OpenAI (United States), which generates and checks the answer and translates passages on request; news questions also go to its web search. Server inference is not fully local or private to your device. Your account email is not sent with the question.</p>
 <h3>Your controls</h3><p>You can edit your profile, export account research, delete individual conversations and sign out of pilot sessions. Anonymous conversations and reading preferences remain in browser storage until you remove them. An account export does not include provider security logs or backups.</p>
 <h3>Identity and research</h3><p>This pilot does not verify passports or collect official votes. Following a topic or choosing a canton is a preference, not evidence of political affiliation or residence. Uploaded profile pictures are stored with your authentication profile. Provider pictures may load from that provider.</p>
 <h3>Contact and removal</h3><p>For access, correction or account-removal requests, contact <a href="mailto:contact@midnight.vote">contact@midnight.vote</a>. We will verify ownership before acting. Legal operator details and a documented retention schedule are being finalized; this notice describes the pilot’s current data flows.</p>
 </>:<><p>Cleisthenes (midnight.vote · Switzerland) is an independent research tool, not a government service or a voting system. You remain responsible for checking original sources before relying on an AI answer.</p><h3>Use the evidence responsibly</h3><p>Summaries, translations and generated answers can be incomplete or wrong. A quoted statement is not necessarily a party’s position or a person’s current view. Source dates, speakers and context matter.</p><h3>Your account</h3><p>Keep authentication links and codes private. Do not use the service to impersonate others, harass people, obtain unauthorized access or upload material you do not have permission to use. Public sources remain subject to their publishers’ rights.</p><h3>Pilot availability</h3><p>Features and source coverage may change. Export research you want to keep. For support or concerns, contact <a href="mailto:contact@midnight.vote">contact@midnight.vote</a>.</p><p className="settings-hint">Pilot usage guidance. Final operator details and legal terms are pending owner review.</p></>}</article>;
}
