import React,{useEffect,useState,useRef} from 'react';
import {pilotApi as api} from '../services/pilotApi.js';
import './parliament.css';

import Chamber from './Chamber.jsx';
import SessionCoverage from './SessionCoverage.jsx';
import VideoSearch from './VideoSearch.jsx';
import DebateReader from './DebateReader.jsx';
import AskEntry from './AskEntry.jsx';
import PoliticianProfile from './PoliticianProfile.jsx';

export default function ParliamentExplorer({language='en',onContext,onAsk,onProfile,user,onAccount}){
 const fr=language==='fr';const label=(en,frText)=>fr?frText:en;
 const [data,setData]=useState(null),[archive,setArchive]=useState(null),[profiles,setProfiles]=useState(null),[processing,setProcessing]=useState(null),[tab,setTab]=useState('projects'),[filter,setFilter]=useState(''),[stage,setStage]=useState('current'),[detail,setDetail]=useState(null),[kind,setKind]=useState('business'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const request=useRef(0);
 useEffect(()=>{try{const business=new URLSearchParams(location.search).get('business');const previous=business?{kind:'business',id:business}:JSON.parse(sessionStorage.getItem('civic-parliament-selection')||'null');if(previous)open(previous.kind,previous.id);}catch{}},[]);
 const [attempt,setAttempt]=useState(0),[visible,setVisible]=useState(60);
 // A slow archive query must end in a visible, retryable state rather than an endless spinner.
 useEffect(()=>{let active=true;setError('');const timer=setTimeout(()=>active&&setError('timeout'),20000);api.parliament().then(d=>{if(active){clearTimeout(timer);setError('');setData(d);}}).catch(()=>{if(active){clearTimeout(timer);setError('failed');}});return()=>{active=false;clearTimeout(timer);request.current++;};},[attempt]);
 useEffect(()=>setVisible(60),[tab,filter,stage]);
 useEffect(()=>{let active=true;Promise.allSettled([api.archiveCoverage(),api.profileCoverage(),api.processingBacklog()]).then(([a,p,g])=>{if(!active)return;if(a.status==='fulfilled')setArchive(a.value);if(p.status==='fulfilled')setProfiles(p.value);if(g.status==='fulfilled')setProcessing(g.value);});return()=>{active=false;};},[]);
 const date=v=>v?new Date(v).toLocaleDateString(fr?'fr-CH':'en-GB'):'—';
 async function open(type,id){const n=++request.current;setBusy(true);setError('');try{const d=await(type==='person'?api.parliamentPerson(id):api.parliamentBusiness(id));if(n!==request.current)return;setKind(type);setDetail(d);try{sessionStorage.setItem('civic-parliament-selection',JSON.stringify({kind:type,id}));}catch{}onContext?.({kind:type,id:d.id,title:d.name||d.title});}catch{if(n===request.current)setError(label('Record unavailable.','Document indisponible.'));}finally{if(n===request.current)setBusy(false);}}
 if(!data)return <section className="parliament" aria-busy={!error}><h1>{label('Parliament','Parlement')}</h1>{error?<div className="parliament-load-error" role="alert"><p>{error==='timeout'?label('The official records are taking longer than usual to load.','Le chargement des données officielles prend plus de temps que prévu.'):label('The official records could not be loaded.','Les données officielles n’ont pas pu être chargées.')}</p><button onClick={()=>setAttempt(n=>n+1)}>{label('Try again','Réessayer')}</button></div>:<div className="parliament-skeleton" role="status"><span className="sr-only">{label('Loading official records…','Chargement des données officielles…')}</span><i/><i/><i/><i/></div>}</section>;
 const rows=(tab==='people'?data.people:data.businesses).filter(r=>(tab==='people'||stage==='all'||(stage==='current'&&data.sessions?.some(s=>s.start?.slice(0,10)<=new Date().toISOString().slice(0,10)&&s.end?.slice(0,10)>=new Date().toISOString().slice(0,10)&&s.businessIds.includes(r.id)))||r.statusGroup===stage)&&`${r.name||r.title} ${r.canton||''} ${r.number||''} ${r.party||''}`.toLowerCase().includes(filter.toLowerCase()));
 const last=data.runs.find(r=>r.status==='complete');
 return <section className="parliament"><div className="parliament-heading"><p className="eyebrow">{label('The public record','Les archives publiques')}</p><h1>{label('Follow the decision.','Suivre la décision.')}</h1><p>{label('Discover proposals, read parliamentary words, and inspect individual votes.','Explorer les objets, lire les interventions et consulter les votes individuels.')}</p></div>
 <Chamber onProfile={onProfile} onAsk={onAsk} user={user} onAccount={onAccount}/>
 <div className="parliament-coverage"><strong>{data.counts.business||0} {label('proposals','objets')} · {data.counts.vote||0} {label('proposal roll calls','scrutins des objets')} · {data.counts.speech||0} {label('text passages','extraits')}</strong><span>{label('Official snapshot','Données officielles consultées le')} {date([last?.sourceRetrievedAt||last?.finished,...(data.sessions||[]).map(s=>s.retrievedAt)].filter(Boolean).sort().at(-1))}</span><p>{label('Official records from imported sessions and proposals. Open session coverage to see what is searchable and what has been video-processed. This is a retrieved snapshot.','Données officielles des sessions et objets importés. Consultez la couverture pour distinguer les textes indexés des vidéos traitées.')}</p></div>
 {(archive?.status==='declared'||profiles)&&<details className="coverage-ledger"><summary><span>{label('Coverage ledger','Registre de couverture')}</span><strong>{archive?.totals?.stages?.text?.complete||0}/{archive?.totals?.sessions||0} {label('sessions text-indexed','sessions avec texte indexé')} · {profiles?.totals?.enriched||0}/{profiles?.totals?.profiles||0} {label('profiles enriched','profils enrichis')}</strong></summary><div className="coverage-ledger-grid">{archive?.status==='declared'&&<section><p className="eyebrow">{label('Declared archive','Archive déclarée')}</p><h3>{archive.boundary.fromYear}–{archive.boundary.toYear}</h3><dl><dt>{label('Official passages','Extraits officiels')}</dt><dd>{archive.totals.officialTextPassages.toLocaleString()}</dd><dt>{label('Recording jobs','Enregistrements à traiter')}</dt><dd>{(processing?.jobs||archive.totals.recordingJobs).toLocaleString()}</dd><dt>{label('Pending Canary ASR','Transcriptions Canary en attente')}</dt><dd>{processing?.pendingAsr?.toLocaleString()||'—'}</dd><dt>{label('Completed Canary jobs','Transcriptions Canary terminées')}</dt><dd>{processing?.states?.asrComplete?.toLocaleString()||archive.totals.canaryReceipts.toLocaleString()}</dd>{archive.totals.officialVideoMissing>0&&<><dt>{label('No official video','Sans vidéo officielle')}</dt><dd>{archive.totals.officialVideoMissing.toLocaleString()}</dd></>}<dt>{label('E5 chunks','Fragments E5')}</dt><dd>{archive.totals.e5Chunks.toLocaleString()}</dd></dl><small>{label('Text, media, ASR, embeddings and timing review are measured separately.','Le texte, les médias, la transcription, les embeddings et la validation temporelle sont mesurés séparément.')}</small></section>}{profiles&&<section><p className="eyebrow">{label('Public profiles','Profils publics')}</p><h3>{profiles.totals.active} {label('active representatives','représentants actifs')}</h3><dl><dt>{label('Official profiles found','Profils officiels trouvés')}</dt><dd>{profiles.totals.profiles}</dd><dt>{label('Fully enriched','Entièrement enrichis')}</dt><dd>{profiles.totals.enriched}</dd><dt>{label('Pending enrichment','En attente')}</dt><dd>{profiles.totals.pending}</dd><dt>{label('Verified portraits','Portraits vérifiés')}</dt><dd>{profiles.totals.verifiedPortraits}</dd></dl><small>{label('Missing profile stages remain visible instead of being interpreted as missing political activity.','Les étapes manquantes restent visibles et ne sont pas interprétées comme une absence d’activité politique.')}</small></section>}</div></details>}
 <div className="parliament-tools"><VideoSearch key={language} language={language} onAsk={onAsk}/><SessionCoverage sessions={data.sessions} language={language}/></div><div className="parliament-layout"><aside className="parliament-directory"><div className="tabs"><button aria-pressed={tab==='projects'} onClick={()=>{setTab('projects');setFilter('');}}>{label('Proposals','Objets')}</button><button aria-pressed={tab==='people'} onClick={()=>{setTab('people');setFilter('');}}>{label('People','Personnes')}</button></div><input aria-label={label('Filter records','Filtrer les documents')} placeholder={label('Name, canton or proposal…','Nom, canton ou objet…')} value={filter} onChange={e=>setFilter(e.target.value)}/>{tab==='projects'&&<select aria-label={label('Parliamentary stage','Étape parlementaire')} value={stage} onChange={e=>setStage(e.target.value)}><option value="current">{label('Current session · imported','Session actuelle · importée')}</option><option value="all">{label('All parliamentary stages','Toutes les étapes')}</option><option value="proceedings">{label('In proceedings','En cours')}</option><option value="concluded">{label('Concluded','Terminés')}</option><option value="unclassified">{label('Stage to review','Étape à vérifier')}</option></select>}<div className="parliament-records">{tab==='projects'&&data.businessTotals&&<p className="parliament-records-note">{label(`Showing ${data.businessTotals.shown.toLocaleString()} recent proposals with imported debate, of ${data.businessTotals.archive.toLocaleString()} in the archive. Ask Cleisthenes to search the full record.`,`${data.businessTotals.shown.toLocaleString()} objets récents avec débats importés sur ${data.businessTotals.archive.toLocaleString()} dans l’archive. Demandez à Cleisthenes pour chercher dans tout le corpus.`)}</p>}{rows.slice(0,visible).map(r=><button key={r.id} aria-pressed={detail?.id===r.id&&kind===(tab==='people'?'person':'business')} onClick={()=>open(tab==='people'?'person':'business',r.id)}><small>{r.number||r.canton||'CH'} · {tab==='people'?r.party||r.group:r.status}</small><strong>{tab==='people'&&r.portraitUrl&&<img className="directory-portrait" src={r.portraitUrl} alt="" loading="lazy" onError={e=>e.currentTarget.hidden=true}/ >}{r.name||r.title}</strong>{tab==='projects'&&<small>{r.passageCount||0} {label('passages available','extraits disponibles')}</small>}{r.modified&&<small>{label('Updated','Actualisé le')} {date(r.modified)}</small>}</button>)}{rows.length>visible&&<button className="parliament-more" onClick={()=>setVisible(v=>v+60)}>{label(`Show more · ${(rows.length-visible).toLocaleString()} remaining`,`Afficher plus · ${(rows.length-visible).toLocaleString()} restants`)}</button>}{!rows.length&&<p>{label('No records in this imported collection.','Aucun document dans cette collection importée.')}</p>}</div></aside>
 <div className="parliament-workspace">{!detail?<div className="parliament-welcome"><h2>{label('A proposal has a history.','Chaque objet a une histoire.')}</h2><p>{label('Choose a proposal or a person to explore their words, sources and recorded votes.','Choisissez un objet ou une personne pour explorer ses interventions, ses sources et ses votes.')}</p></div>:<article className="parliament-detail"><p className="eyebrow">{kind==='person'?label('Public representative','Représentant public'):detail.number}</p><h2>{detail.name||detail.title}</h2>{kind==='business'?<><p><strong>{label('Parliamentary status','État parlementaire')}:</strong> {detail.status} · {date(detail.statusDate)}</p><a href={detail.officialUrl} target="_blank" rel="noreferrer">{label('Open Curia Vista ↗','Consulter Curia Vista ↗')}</a>{detail.popularVote&&<p className="notice">{label('Separate popular vote: completed on','Votation populaire distincte : terminée le')} {date(detail.popularVote.date)} · {label('accepted','accepté')}. <a href={detail.popularVote.sourceUrl} target="_blank" rel="noreferrer">{label('Official result','Résultat officiel')}</a></p>}<details><summary>{label('Parliamentary timeline','Chronologie parlementaire')} ({detail.timeline.length})</summary><ol>{detail.timeline.map(e=><li key={e.id}><time>{date(e.date)}</time> — <a href={e.sourceUrl} target="_blank" rel="noreferrer">{e.label} ↗</a></li>)}</ol>{!detail.timeline.length&&<p>{label('Timeline not imported.','Chronologie non importée.')}</p>}</details></>:<PoliticianProfile key={detail.id} person={detail} language={language} onUpdate={d=>{setDetail(current=>current?.id===d.id?d:current);setData(old=>({...old,people:old.people.map(p=>p.id===d.id?d:p)}));}}/>}
 {kind==='business'&&<details><summary>{label('Recorded votes','Votes enregistrés')} ({detail.votes.length})</summary>{detail.votes.map(v=><div className="parliament-vote" key={v.id}><strong>{date(v.date)} · {v.subject||v.billTitle||v.title||v.voteId}</strong>{kind==='person'&&<p>{label('Recorded decision','Décision enregistrée')}: {v.decisionText||label('Label unavailable','Libellé indisponible')} · {v.group}</p>}<p>{label('Yes means','Oui signifie')}: {v.meaningYes||'—'}<br/>{label('No means','Non signifie')}: {v.meaningNo||'—'}</p><a href={v.sourceUrl||v.officialUrl} target="_blank" rel="noreferrer">{label('Official record ↗','Donnée officielle ↗')}</a></div>)}{!detail.votes.length&&<p>{label('No vote history imported for this selection.','Aucun historique de votes importé pour cette sélection.')}</p>}</details>}</article>}
 <div role="status">{busy?label('Loading record…','Chargement du document…'):error}</div><AskEntry language={language} context={detail?{kind,id:detail.id,title:detail.name||detail.title}:null} onOpen={onAsk}/>

 <DebateReader key={(detail?.id||'all')+kind} language={language} sessions={data.sessions} business={kind==='business'?detail?.id:undefined} person={kind==='person'?detail?.id:undefined}/></div></div></section>;
}
