import MfaChallenge from './MfaChallenge.jsx';
import VerifyEmail from './VerifyEmail.jsx';
import LegalNotice from './LegalNotice.jsx';
import Feedback from './Feedback.jsx';
import React,{useState,useEffect,useRef} from 'react';
import {ArrowRight,ArrowLeft,ArrowUpRight,BookOpen,BookmarkSimple,Check,Globe,Hamburger,ShieldCheck,FileText,MagnifyingGlass,Scales,Sparkle,X,Download,UserCircle,GearSix} from '@phosphor-icons/react';
import {pilotApi as api} from '../services/pilotApi.js';
import {dictionaries,languageNames,categoryNames} from './i18n.js';
import './pilot.css';
import ParliamentExplorer from './ParliamentExplorer.jsx';
import Cleisthenes from './Cleisthenes.jsx';
import AskEntry from './AskEntry.jsx';
import './ux-refinement.css';
import CivicLanding from './CivicLanding.tsx';
import Settings,{readPreferences} from './Settings.jsx';
import './brand.css';
import SavedBriefs from './SavedBriefs.jsx';
import AuthPanel from './AuthPanel.jsx';
import Dashboard from './Dashboard.jsx';
import ChatsPage from './ChatsPage.jsx';
import LanguageMenu from './LanguageMenu.jsx';
import Topics from './Topics.jsx';
import MemberPage from './MemberPage.jsx';
import './workspace.css';
import {attribution} from './attributions.js';

const initialRoute=()=>{const q=new URLSearchParams(location.search);return {id:q.get('issue'),view:q.get('view')||(q.get('issue')?'explore':'home')};};
export function SwissPilot(){
 const [lang,setLang]=useState(()=>{try{return localStorage.getItem('swiss-language')||'en';}catch{return 'en';}});const t=dictionaries[lang]||dictionaries.en;
 const [preferences,setPreferences]=useState(readPreferences);const [preferenceError,setPreferenceError]=useState('');const [sourceFilter,setSourceFilter]=useState('all');
 function updatePreferences(value){setPreferences(value);if(user)api.putItem('preference','reading',value).catch(()=>setPreferenceError('Account preferences could not sync.'));try{localStorage.setItem('swiss-reading-preferences',JSON.stringify(value));setPreferenceError('');}catch{setPreferenceError('Preferences apply now but could not be saved in this browser.');}}
 const [chatContext,setChatContext]=useState(null);const [chatRequest,setChatRequest]=useState(null);const chatReturn=useRef(null);const researchStates=useRef(new Map());
 function openChat(context,options={}){setChatContext(context);setChatRequest({...options,nonce:Date.now()});}const [route,setRoute]=useState(initialRoute);const [dossiers,setDossiers]=useState([]);const [dossier,setDossier]=useState(null);const [health,setHealth]=useState(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [query,setQuery]=useState('');const [tab,setTab]=useState('overview');const [question,setQuestion]=useState('');const [answer,setAnswer]=useState(null);const [active,setActive]=useState(null);const [selected,setSelected]=useState([]);
 const [user,setUser]=useState(null);const [userLoaded,setUserLoaded]=useState(false);const [saved,setSaved]=useState([]);const [modal,setModal]=useState(null);const [authNote,setAuthNote]=useState('');const dialog=useRef(null);const video=useRef(null);const [videoError,setVideoError]=useState(false);const requestId=useRef(0);
 const local=value=>value?.[lang]||value?.en||'';const date=value=>new Intl.DateTimeFormat(lang==='rm'?'de-CH':lang,{day:'numeric',month:'long',year:'numeric'}).format(new Date(value+'T12:00:00'));
 const category=value=>categoryNames[lang]?.[value]||value;
 function navigate(id=null,view='explore'){const url=new URL(location.href);url.search='';if(id)url.searchParams.set('issue',id);if(view!=='home')url.searchParams.set('view',view);url.hash='';history.pushState({},'',url);setRoute({id,view});setError('');window.scrollTo(0,0);}
 async function boot(){try{const h=await api.health();setHealth(h);try{setDossiers(await api.dossiers());}catch(e){if(![401,403].includes(e.status))throw e;}}catch{setError(t.error);}}
 useEffect(()=>{boot();api.me().then(setUser).catch(()=>{}).finally(()=>setUserLoaded(true));const pop=()=>setRoute(initialRoute());addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop);},[]);
 useEffect(()=>{const q=new URLSearchParams(location.search),h=new URLSearchParams(location.hash.slice(1));if(h.get('access_token')){history.replaceState({},'',location.pathname+'?view=dashboard');setRoute({id:null,view:'dashboard'});setModal('auth');setError('This older email link cannot establish a secure session. Sign in after verification, or request a fresh recovery link.');}else if(q.get('auth')==='retry')setModal('auth');else if(q.get('auth')==='reset')setModal('reset');else if(['cancelled','failed'].includes(q.get('auth'))){setModal('auth');setError(q.get('auth')==='cancelled'?'Sign-in was cancelled.':'The sign-in link could not finish. Use the same browser that requested it, or request a fresh link.');}else if(q.get('auth')==='complete')history.replaceState({},'',location.pathname+'?view=dashboard');},[]);
 useEffect(()=>{const onAccess=e=>{if(['SIGN_IN_REQUIRED','SESSION_EXPIRED'].includes(e.detail?.code)){setUser(null);setModal('auth');}else api.me().then(setUser).catch(()=>setUser(null));};addEventListener('civic-auth',onAccess);return()=>removeEventListener('civic-auth',onAccess);},[]);
 useEffect(()=>{if(user?.emailVerified&&!dossiers.length)api.dossiers().then(setDossiers).catch(()=>{});},[user?.emailVerified]);
 useEffect(()=>{if(!user)return;let live=true;api.items('preference').then(rows=>{if(live){const p=rows.find(x=>x.id==='reading')?.payload;if(p)setPreferences(p);}}).catch(()=>setPreferenceError('Account preferences could not be loaded.'));return()=>{live=false;};},[user?.id]);
 useEffect(()=>{const jump=e=>{const next=new URL(e.detail,location.href);history.pushState({},'',next);setRoute(initialRoute());window.scrollTo(0,0);};addEventListener('civic-navigate',jump);const askAnywhere=e=>openChat(e.detail?.context||null,e.detail?.options||{});addEventListener('civic-ask',askAnywhere);return()=>{removeEventListener('civic-navigate',jump);removeEventListener('civic-ask',askAnywhere);};},[]);
 useEffect(()=>{document.documentElement.lang=lang;document.title='Cleisthenes — Swiss civic companion';try{localStorage.setItem('swiss-language',lang);}catch{setPreferenceError('Language applies now but could not be saved in this browser.');}setAnswer(null);requestId.current++;setBusy(false);},[lang]);
 useEffect(()=>{let ignore=false;const remembered=researchStates.current.get(route.id);setDossier(null);setAnswer(null);setActive(null);setSelected(remembered?.selected||[]);setSourceFilter(remembered?.sourceFilter||'all');setQuestion('');setTab(remembered?.tab||'overview');requestId.current++;setBusy(false);if(route.id)api.dossier(route.id).then(d=>{if(!ignore){setDossier(d);if(remembered?.activeId)setActive(d.evidence.find(e=>e.id===remembered.activeId)||null);}}).catch(()=>{if(!ignore)setError(t.error);});return()=>{ignore=true;};},[route.id]);
 useEffect(()=>{if(route.id&&dossier?.id===route.id)researchStates.current.set(route.id,{selected,tab,sourceFilter,activeId:active?.id});},[route.id,dossier?.id,selected,tab,sourceFilter,active]);
 useEffect(()=>{if(user)api.saved().then(setSaved).catch(e=>{if(e.status===401)setUser(null);setError('Saved sources could not be loaded. Please try again.');});else setSaved([]);},[user]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();},[modal]);
 useEffect(()=>{setVideoError(false);if(active?.kind==='video'&&video.current)video.current.currentTime=active.start;},[active]);
 const currentText=e=>e.translations?.[lang]||e.text;
 async function ask(action='explain',q=question){setError('');setBusy(true);const rid=++requestId.current;try{const result=await api.ask({dossierId:dossier.id,action,question:q,language:lang});if(rid===requestId.current)setAnswer(result);}catch{if(rid===requestId.current)setError(t.error);}finally{if(rid===requestId.current)setBusy(false);}}
 async function save(e){if(!user){setAuthNote('');setModal('auth');return;}try{setSaved(await (saved.some(s=>s.id===e.id)?api.remove(e.id):api.save(e.id)));}catch(err){if(err.status===401){setUser(null);setModal('auth');}setError(t.error);}}
 async function exportBrief(){try{const {markdown}=await api.brief({dossierId:dossier.id,evidenceIds:selected,language:lang});if(user)await api.putItem('brief',crypto.randomUUID(),{title:local(dossier.shortTitle),markdown,dossierId:dossier.id,evidenceIds:selected});const url=URL.createObjectURL(new Blob([markdown],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`midnight-${dossier.id}-brief.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setError(t.error);}}
 async function authenticate(event){event.preventDefault();setAuthNote('');setBusy(true);const data=new FormData(event.currentTarget);try{const payload={email:data.get('email'),password:data.get('password')};if(event.nativeEvent.submitter?.value==='signup'){await api.signup(payload);setAuthNote(t.checkEmail);}else{setUser(await api.login(payload));setModal(null);}}catch{setAuthNote(t.accountError);}finally{setBusy(false);}}
 function inspect(e){setActive(e);setTimeout(()=>document.getElementById('evidence-inspector')?.scrollIntoView({behavior:'smooth',block:'nearest'}),30);}
 function EvidenceCard({e,compact=false}){const isSaved=saved.some(s=>s.id===e.id);return <article className={`evidence-card ${compact?'compact':''}`}><div className="evidence-meta"><span>{e.kind==='video'?t.publisherCaption:t.editorial}</span><span>{e.language.toUpperCase()}</span></div><h3>{e.sourceKind==='federal-council-explainer'?t.federalExplainer:attribution(e.attribution,lang)}</h3><p>{currentText(e)}</p><div className="card-actions"><button onClick={()=>inspect(e)}><ArrowUpRight/>{t.inspect}</button><button aria-label={isSaved?t.remove:t.save} onClick={()=>save(e)}><BookmarkSimple weight={isSaved?'fill':'regular'}/></button>{<button aria-label={selected.includes(e.id)?t.unselect:t.select} aria-pressed={selected.includes(e.id)} onClick={()=>setSelected(s=>s.includes(e.id)?s.filter(id=>id!==e.id):[...s,e.id])}>{selected.includes(e.id)?<Check/>:<FileText/>}</button>}</div></article>;}
 const visible=dossiers.filter(d=>(local(d.shortTitle)+' '+local(d.summary)).toLowerCase().includes(query.toLowerCase()));
 if(user?.mfaRequired)return <div className="swiss-app"><MfaChallenge onVerified={u=>{setUser(u);setError('');}}/><button className="text-button" onClick={async()=>{await api.logout();setUser(null);}}>Sign out</button></div>;
 // Beyond the landing page the app is for verified accounts whenever the server's access policy says so.
 const gated=Boolean(health?.access&&health.access!=='open');
 if((route.view!=='home'||route.id)&&(!health||(gated&&!userLoaded)))return <div className="swiss-app access-check" role="status" aria-live="polite"><p>Checking your account…</p></div>;
 if((route.view==='home'&&!route.id)||(gated&&!user))return <CivicLanding key={gated&&!user?'account':'home'} user={user} onUser={setUser} onNavigate={navigate} language={lang} reduceMotion={preferences.reduceMotion} allowGuest={!gated} openAccount={gated&&!user&&!(route.view==='home'&&!route.id)}/>;
 if(gated&&!user.emailVerified)return <VerifyEmail user={user} onUser={setUser}/>;
 return <div className="swiss-app" data-large-text={preferences.largeText} data-reduce-motion={preferences.reduceMotion}><a className="skip" href="#main">{t.overview}</a><header className="swiss-header"><button className="wordmark wordmark-cleisthenes" aria-label="Cleisthenes home" onClick={()=>navigate(null,'dashboard')}><img src={import.meta.env.BASE_URL+'brand/cleisthenes-bust.png'} alt=""/><span>Cleisthenes<small>{t.pilot}</small></span></button><nav aria-label="Main"><button className={route.view==='dashboard'?'current':''} onClick={()=>navigate(null,'dashboard')}>Home</button><button className={route.view==='parliament'?'current':''} onClick={()=>navigate(null,'parliament')}>{lang==='fr'?'Parlement':'Parliament'}</button><button className={['explore','research'].includes(route.view)?'current':''} onClick={()=>navigate()}>{lang==='fr'?'Thèmes et votations':'Topics & votes'}</button><button className={route.view==='chats'?'current':''} onClick={()=>navigate(null,'chats')}>{lang==='fr'?'Mes discussions':'My chats'}</button></nav><div className="header-tools"><button className="header-feedback" onClick={()=>setModal('feedback')}>{lang==='fr'?'Commentaire':'Feedback'}</button><LanguageMenu value={lang} names={languageNames} label={t.language} onChange={setLang}/><button className="settings-button" aria-label={lang==='fr'?'Réglages':'Settings'} onClick={()=>navigate(null,'settings')}><GearSix/></button><button className="account-button" aria-label={user?t.account:t.signin} onClick={()=>{setAuthNote('');user?navigate(null,'settings'):setModal('auth');}}>{user?.avatar?<img className="header-avatar" src={user.avatar} alt="" referrerPolicy="no-referrer"/>:<UserCircle/>}<span>{user?(user.firstName||user.name?.split(/\s+/)[0]||t.account):t.signin}</span></button></div></header>
 {error&&<div role="alert" className="error-banner">{error}<button onClick={()=>{setError('');boot();}}>{t.retry}</button></div>}
 {!['en','fr'].includes(lang)&&<div className="locale-note">{languageNames[lang]} · {lang==='rm'?'Texts uffizials e navigaziun; ulteriurs texts per englais.':'Navigation and dossier summaries translated; detailed research falls back to the available source language.'}</div>}
 <main id="main" className={route.view==='research'?'research-main':''}>
 {route.view==='dashboard'&&<Dashboard user={user} dossiers={dossiers} language={lang} onNavigate={navigate} onAsk={openChat} onAccount={()=>setModal('auth')}/>}
 {route.view==='profile'&&<MemberPage id={new URLSearchParams(location.search).get('person')} language={lang} user={user} onAsk={openChat} onAccount={()=>setModal('auth')}/>}
 {!route.id&&['explore','research'].includes(route.view)&&<Topics dossiers={dossiers} language={lang} onNavigate={navigate} onAsk={openChat}/>}
 {route.id&&!dossier&&!error&&<p role="status">{t.working}</p>}
 {dossier&&<><button className="back-button" onClick={()=>navigate()}><ArrowLeft/>{t.back}</button><section className="dossier-heading"><p className="eyebrow">{category(dossier.category)} <span> / {t.historical}</span></p><h1>{local(dossier.shortTitle)}</h1><p>{local(dossier.summary)}</p><div className="dossier-facts"><span>{date(dossier.date)}</span><span className={`outcome ${dossier.result}`}>{t[dossier.result]}</span><span>{dossier.readingMinutes} {t.minutes}</span></div></section>
 <div className="workbench"><div className="reading-pane"><div className="tabs" role="tablist">{['overview','debate','timeline','evidence'].map(key=><button key={key} role="tab" aria-selected={tab===key} onClick={()=>setTab(key)}>{{overview:'Overview',debate:'Debate',timeline:'Timeline',evidence:'Sources'}[key]}</button>)}</div>
 {tab==='overview'&&dossier.evidence.some(e=>e.kind==='video')&&<section className="official-videos"><p className="eyebrow">{t.watchOfficial}</p><p className="muted">{t.videoCoverage}</p><div className="skill-actions">{dossier.evidence.filter(e=>e.kind==='video').map(e=><button key={e.id} onClick={()=>inspect(e)}>{languageNames[e.language]} ↗</button>)}</div></section>}
 {tab==='overview'&&<section className="overview-panel"><p className="eyebrow">{t.voteContext}</p><h2>{local(dossier.question)}</h2><p className="muted">{t.archiveNote}</p><EvidenceCard e={dossier.evidence[0]}/><div className="argument-preview">{dossier.evidence.filter(e=>['support','opposition'].includes(e.stance)).map(e=><div key={e.id}><span className="argument-label">{e.stance==='support'?t.support:t.opposition}</span><p>{currentText(e)}</p><button className="text-button" onClick={()=>inspect(e)}>{t.source}<ArrowUpRight/></button></div>)}</div></section>}
 {tab==='debate'&&<section className="comparison-grid">{['support','opposition'].map(stance=><div key={stance}><h2><Scales/>{t[stance]}</h2>{dossier.evidence.filter(e=>e.stance===stance).map(e=><EvidenceCard key={e.id} e={e}/>)}</div>)}</section>}
 {tab==='timeline'&&<section className="overview-panel"><h2>Ballot timeline</h2><ol><li><time>{date(dossier.date)}</time> · Historical popular vote · {t[dossier.result]}</li></ol><p>Open the official sources for the full legislative history.</p>{dossier.sources.map(s=><p key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a></p>)}</section>}
 {tab==='evidence'&&<section className="evidence-list"><div className="source-guide"><p className="eyebrow">{lang==='fr'?'Remonter à l’origine':'Go back to the original'}</p><h2>{lang==='fr'?'Ce qui étaye ce dossier.':'What this dossier is based on.'}</h2><p>{lang==='fr'?'Les résumés éditoriaux expliquent les sources. Les vidéos officielles présentent les votations ; ce ne sont pas des interventions parlementaires. Ouvrez chaque source pour vérifier le contexte.':'Editorial summaries explain the sources. Official videos explain the ballot; they are not parliamentary speeches. Open a source to check its context.'}</p><label>{lang==='fr'?'Afficher ':'Show '}<select aria-label="Source type" value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)}><option value="all">{lang==='fr'?'Toutes les sources':'All sources'}</option><option value="editorial">{lang==='fr'?'Résumés éditoriaux':'Editorial summaries'}</option><option value="video">{lang==='fr'?'Vidéos officielles':'Official videos'}</option></select></label></div>{dossier.evidence.filter(e=>sourceFilter==='all'||(sourceFilter==='video'?e.kind==='video':e.kind!=='video')).map(e=><EvidenceCard e={e} key={e.id}/>)}{!dossier.evidence.some(e=>sourceFilter==='all'||(sourceFilter==='video'?e.kind==='video':e.kind!=='video'))&&<p>{lang==='fr'?'Aucune source de ce type dans ce dossier.':'No sources of this type in this dossier.'}</p>}</section>}
 <AskEntry language={lang} dossier context={{kind:'dossier',id:dossier.id,title:local(dossier.shortTitle)}} onOpen={openChat}/>
 </div><aside className="source-pane" id="evidence-inspector" aria-label={t.evidence}>{active?<><div className="inspector-heading"><span className="eyebrow">{active.kind==='video'?t.video:t.document} / {active.language.toUpperCase()}</span><button aria-label={t.close} onClick={()=>setActive(null)}><X/></button></div><h2>{active.sourceKind==='federal-council-explainer'?t.federalExplainer:attribution(active.attribution,lang)}</h2>{active.kind==='video'&&<><video ref={video} controls preload="metadata" key={active.id} src={active.mediaUrl} onLoadedMetadata={()=>{video.current.currentTime=active.start;}} onError={()=>setVideoError(true)}/><button className="secondary" onClick={()=>{video.current.currentTime=active.start;video.current.play().catch(()=>setVideoError(true));}}>{t.play}</button>{videoError&&<p role="alert">{t.videoError}</p>}</>}<p className="eyebrow">{active.reviewState==='official-publisher-captions'?t.publisherCaption:t.editorial}</p><blockquote>{active.text}</blockquote>{active.translations?.[lang]&&active.translations[lang]!==active.text&&<><span className="eyebrow">{t.translation}</span><p>{active.translations[lang]}</p></>}<a className="source-link" href={active.source.url} target="_blank" rel="noreferrer">{active.source.title}<ArrowUpRight/></a><small>{active.id} · r{active.revision}<br/>{active.reviewState==='official-publisher-captions'?t.publisherCaption:t.review}</small><button className="secondary" onClick={()=>save(active)}><BookmarkSimple/>{saved.some(s=>s.id===active.id)?t.remove:t.save}</button></>:<><FileText size={32}/><h2>{t.readSource}</h2><p>{dossier.evidence.some(e=>e.kind==='video')?t.videoCoverage:t.coverage}</p><div className="source-directory">{dossier.sources.map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.title}<ArrowUpRight/></a>)}</div></>}
 {<section className="brief-builder"><h3>{t.selected} <span>{selected.length}</span></h3>{selected.length?<><ul>{selected.map(id=><li key={id}>{dossier.evidence.find(e=>e.id===id)?.attribution}<button aria-label={t.remove} onClick={()=>setSelected(s=>s.filter(x=>x!==id))}><X/></button></li>)}</ul><button className="primary" onClick={exportBrief}><Download/>{t.export}</button></>:<p>{t.emptySelection}</p>}</section>}
 </aside></div>{dossier.id==='eid'&&<section className="romansh-passage"><span className="eyebrow">{t.rm}</span><p lang="rm">{dossier.evidence.find(e=>e.id==='rm-civic-passage')?.text}</p><small>{t.rmNote}</small><a href="https://www.bk.admin.ch/rm" target="_blank" rel="noreferrer">Chanzlia federala <ArrowUpRight/></a></section>}</>}
 {['privacy','terms'].includes(route.view)&&<section className="preferences-card"><LegalNotice kind={route.view}/></section>}
 {route.view==='settings'&&<><Settings language={lang} onLanguage={setLang} preferences={preferences} onPreferences={updatePreferences} user={user} onUser={setUser} onSaved={()=>navigate(null,'saved')} authAvailable={health?.auth} onAccount={()=>setModal('auth')} onExplore={()=>navigate(null,'parliament')}/>{preferenceError&&<p role="status">{preferenceError}</p>}</>}
 {route.view==='parliament'&&<ParliamentExplorer user={user} onAccount={()=>setModal('auth')} onProfile={id=>{navigate(null,'profile');const u=new URL(location.href);u.searchParams.set('person',id);history.replaceState({},'',u);setRoute({id:null,view:'profile'});}} language={lang} onContext={setChatContext} onAsk={openChat}/>}
 {route.view==='saved'&&<section className="saved-page"><p className="eyebrow">{t.saved}</p><h1>{t.savedTitle}</h1><p>{user?t.savedIntro:t.loginNeeded}</p>{!user?<button className="primary" onClick={()=>setModal('auth')}>{t.signin}<ArrowRight/></button>:saved.length?<div className="dossier-grid">{saved.map(e=><article className="evidence-card" key={e.id}><h3>{e.sourceKind==='federal-council-explainer'?t.federalExplainer:attribution(e.attribution,lang)}</h3><p>{currentText(e)}</p><button onClick={()=>navigate(e.dossierId,'research')}>{t.read}<ArrowRight/></button><button onClick={()=>save(e)}>{t.remove}</button></article>)}</div>:<p>{t.emptySaved}</p>}</section>}
 {route.view==='saved'&&<SavedBriefs user={user} onNavigate={navigate}/>}{route.view==='chats'&&<ChatsPage user={user} language={lang} onNavigate={navigate}/>}
 </main>{route.view==='chat'?null:<footer className="swiss-footer footer-v2"><div className="footer-brand"><img src={import.meta.env.BASE_URL+'brand/cleisthenes-bust.png'} alt=""/><div><strong>Cleisthenes</strong><small>{lang==='fr'?'Votre compagnon civique suisse':'Your Swiss civic companion'} · midnight.vote</small></div></div><nav className="footer-links" aria-label={lang==='fr'?'Pied de page':'Footer'}><button onClick={()=>navigate(null,'home')}>{lang==='fr'?'À propos':'About Cleisthenes'}</button><button onClick={()=>setModal('identity')}><ShieldCheck/>{t.privacy}</button><button onClick={()=>navigate(null,'privacy')}>{lang==='fr'?'Confidentialité':'Privacy'}</button></nav><div className="footer-feedback"><p>{lang==='fr'?'Une erreur, une idée ? Dites-le-nous.':'Spotted something wrong, or have an idea?'}</p><button onClick={()=>setModal('feedback')}>{lang==='fr'?'Envoyer un commentaire':'Send feedback'}</button><small>{lang==='fr'?'ou écrivez à':'or email'} <a href="mailto:contact@midnight.vote">contact@midnight.vote</a></small></div><p className="footer-legal">{t.independent} · {t.noVote}</p></footer>}
 <Cleisthenes user={user} language={lang} expanded={route.view==='chat'} openRequest={chatRequest} onExpand={()=>{if(route.id)setChatContext({kind:'dossier',id:route.id,title:local(dossier?.shortTitle)});chatReturn.current={...route,url:location.href};navigate(null,'chat');}} onCollapse={()=>{const previous=chatReturn.current||{id:null,view:'parliament'};navigate(previous.id,previous.view);if(previous.url){history.replaceState({},'',previous.url);setRoute(initialRoute());}}} context={route.id?{kind:'dossier',id:route.id,title:dossier?.shortTitle?.[lang]||dossier?.shortTitle?.en}:chatContext}/>
 <dialog ref={dialog} onCancel={()=>setModal(null)} onClose={()=>setModal(null)}><button className="dialog-close" aria-label={t.close} onClick={()=>setModal(null)}><X/></button>{modal==='feedback'?<Feedback/>:['auth','reset'].includes(modal)?<AuthPanel user={user} onUser={setUser} onClose={()=>setModal(null)} initialMode={modal==='reset'?'reset':'magic'}/>:<><ShieldCheck size={36}/><p className="eyebrow">{t.concept}</p><h2>{modal==='consent'?t.consentTitle:t.privacy}</h2><p>{modal==='consent'?t.consentText:t.privacyText}</p><button className="primary" onClick={()=>modal==='consent'?setModal(null):setModal('consent')}>{modal==='consent'?t.done:t.consent}<ArrowRight/></button></>}</dialog>
 </div>;
}
